// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// FPV CSR read and write assertions auto-generated by `reggen` containing data structure
// Do Not Edit directly
// TODO: This automation currently only support register without HW write access

`include "prim_assert.sv"
`ifdef UVM
  `include "uvm_macros.svh"
`endif

`ifndef FPV_ON
  `define REGWEN_PATH tb.dut.u_reg
`else
  `define REGWEN_PATH spi_device.u_reg
`endif

// Block: spi_device
module spi_device_csr_assert_fpv import tlul_pkg::*;
    import top_pkg::*;(
  input clk_i,
  input rst_ni,

  // tile link ports
  input tl_h2d_t h2d,
  input tl_d2h_t d2h
);

  import prim_mubi_pkg::*;
`ifdef UVM
  import uvm_pkg::*;
`endif

// Currently FPV csr assertion only support HRO registers.
`ifndef VERILATOR
`ifndef SYNTHESIS

  logic oob_addr_err;

  typedef struct packed {
    logic [TL_DW-1:0] wr_data;
    logic [TL_AW-1:0] addr;
    logic             wr_pending;
    logic             rd_pending;
  } pend_item_t;

  bit disable_sva;

  // mask register to convert byte to bit
  logic [TL_DW-1:0] a_mask_bit;

  assign a_mask_bit[7:0]   = h2d.a_mask[0] ? '1 : '0;
  assign a_mask_bit[15:8]  = h2d.a_mask[1] ? '1 : '0;
  assign a_mask_bit[23:16] = h2d.a_mask[2] ? '1 : '0;
  assign a_mask_bit[31:24] = h2d.a_mask[3] ? '1 : '0;

  // An index used for regwen, access_policy and exp_vals. These arrays all have one element per HRO
  // register, plus an extra dummy entry to represent "non-HRO registers" (avoiding out-of-bounds
  // accesses).
  bit [5:0] hro_idx;
  bit [12:0] normalized_addr;

  `ifdef FPV_ON
    // For FPV, we restrict the pend_trans array by giving its size a smaller upper bound. This
    // reduces the FPV runtime dramatically.
    localparam int PendTransLen = 11;

    // These two assumptions bound h2d.a_source and d2h.d_source for FPV because they are used as
    // indices for the array.
    `ASSUME_FPV(TlulSourceA_M, h2d.a_source >=  0 && h2d.a_source < PendTransLen, clk_i, !rst_ni)
    `ASSUME_FPV(TlulSourceD_M, d2h.d_source >=  0 && d2h.d_source < PendTransLen, clk_i, !rst_ni)
  `else
    localparam int PendTransLen = 2**TL_AIW;
  `endif

  pend_item_t [PendTransLen-1:0] pend_trans;

  // Indexes of pend_trans have a width that depends on the size of the array. These lines extract
  // just the bottom bits (so that the widths match).
  //
  // When in FPV mode, the TlulSource*_M assumptions above ensure that we aren't dropping any
  // nonzero bits. When not in FPV mode, this is a no-op: the a_source and d_source values are of
  // width TL_AIW and we extract that many bits.
  localparam int PendTransIdxWidth = $clog2(PendTransLen);
  logic [PendTransIdxWidth-1:0] a_source_idx, d_source_idx;

  assign a_source_idx = h2d.a_source[PendTransIdxWidth-1:0];
  assign d_source_idx = d2h.d_source[PendTransIdxWidth-1:0];

  // Map register address with hro_idx in exp_vals array.
  always_comb begin: decode_hro_addr_to_idx
    unique case (pend_trans[d_source_idx].addr)
      4: hro_idx = 0;
      8: hro_idx = 1;
      12: hro_idx = 2;
      20: hro_idx = 3;
      28: hro_idx = 4;
      44: hro_idx = 5;
      48: hro_idx = 6;
      52: hro_idx = 7;
      56: hro_idx = 8;
      76: hro_idx = 9;
      80: hro_idx = 10;
      84: hro_idx = 11;
      88: hro_idx = 12;
      92: hro_idx = 13;
      96: hro_idx = 14;
      100: hro_idx = 15;
      104: hro_idx = 16;
      108: hro_idx = 17;
      112: hro_idx = 18;
      116: hro_idx = 19;
      120: hro_idx = 20;
      124: hro_idx = 21;
      128: hro_idx = 22;
      132: hro_idx = 23;
      136: hro_idx = 24;
      140: hro_idx = 25;
      144: hro_idx = 26;
      148: hro_idx = 27;
      152: hro_idx = 28;
      156: hro_idx = 29;
      160: hro_idx = 30;
      164: hro_idx = 31;
      168: hro_idx = 32;
      172: hro_idx = 33;
      176: hro_idx = 34;
      180: hro_idx = 35;
      184: hro_idx = 36;
      188: hro_idx = 37;
      192: hro_idx = 38;
      196: hro_idx = 39;
      200: hro_idx = 40;
      204: hro_idx = 41;
      208: hro_idx = 42;
      212: hro_idx = 43;
      216: hro_idx = 44;
      220: hro_idx = 45;
      224: hro_idx = 46;
      228: hro_idx = 47;
      232: hro_idx = 48;
      2052: hro_idx = 49;
      2060: hro_idx = 50;
      2064: hro_idx = 51;
      2068: hro_idx = 52;
      2072: hro_idx = 53;
      2076: hro_idx = 54;
      2080: hro_idx = 55;
      2084: hro_idx = 56;
      2088: hro_idx = 57;
      2092: hro_idx = 58;
      2100: hro_idx = 59;
      // If the register is not a HRO register, the write data will all update to this default idx.
      default: hro_idx = 60;
    endcase
  end

  // store internal expected values for HW ReadOnly registers
  logic [TL_DW-1:0] exp_vals[61];

  // Word-align the incoming TLUL a_address to obtain the normalized address.
  assign normalized_addr = {h2d.a_address[12:2], 2'b0};

  // Assign regwen to registers. If the register does not have regwen, it will default to value 1.
  logic [60:0] regwen;
  assign regwen[0] = 1;
  assign regwen[1] = 1;
  assign regwen[2] = 1;
  assign regwen[3] = 1;
  assign regwen[4] = 1;
  assign regwen[5] = 1;
  assign regwen[6] = 1;
  assign regwen[7] = 1;
  assign regwen[8] = 1;
  assign regwen[9] = 1;
  assign regwen[10] = 1;
  assign regwen[11] = 1;
  assign regwen[12] = 1;
  assign regwen[13] = 1;
  assign regwen[14] = 1;
  assign regwen[15] = 1;
  assign regwen[16] = 1;
  assign regwen[17] = 1;
  assign regwen[18] = 1;
  assign regwen[19] = 1;
  assign regwen[20] = 1;
  assign regwen[21] = 1;
  assign regwen[22] = 1;
  assign regwen[23] = 1;
  assign regwen[24] = 1;
  assign regwen[25] = 1;
  assign regwen[26] = 1;
  assign regwen[27] = 1;
  assign regwen[28] = 1;
  assign regwen[29] = 1;
  assign regwen[30] = 1;
  assign regwen[31] = 1;
  assign regwen[32] = 1;
  assign regwen[33] = 1;
  assign regwen[34] = 1;
  assign regwen[35] = 1;
  assign regwen[36] = 1;
  assign regwen[37] = 1;
  assign regwen[38] = 1;
  assign regwen[39] = 1;
  assign regwen[40] = 1;
  assign regwen[41] = 1;
  assign regwen[42] = 1;
  assign regwen[43] = 1;
  assign regwen[44] = 1;
  assign regwen[45] = 1;
  assign regwen[46] = 1;
  assign regwen[47] = 1;
  assign regwen[48] = 1;
  assign regwen[49] = 1;
  assign regwen[50] = 1;
  assign regwen[51] = 1;
  assign regwen[52] = 1;
  assign regwen[53] = 1;
  assign regwen[54] = 1;
  assign regwen[55] = 1;
  assign regwen[56] = 1;
  assign regwen[57] = 1;
  assign regwen[58] = 1;
  assign regwen[59] = 1;
  assign regwen[60] = 1;

  // Types of REGWEN supported.
  typedef enum {
    NotRegwen,
    MuBi4Regwen,
    MuBi8Regwen,
    MuBi12Regwen,
    MuBi16Regwen
  } regwen_type_t;

  // The REGWEN type of each register, if any.
  regwen_type_t regwen_types[60];
      assign regwen_types[0] = NotRegwen;
      assign regwen_types[1] = NotRegwen;
      assign regwen_types[2] = NotRegwen;
      assign regwen_types[3] = NotRegwen;
      assign regwen_types[4] = NotRegwen;
      assign regwen_types[5] = NotRegwen;
      assign regwen_types[6] = NotRegwen;
      assign regwen_types[7] = NotRegwen;
      assign regwen_types[8] = NotRegwen;
      assign regwen_types[9] = NotRegwen;
      assign regwen_types[10] = NotRegwen;
      assign regwen_types[11] = NotRegwen;
      assign regwen_types[12] = NotRegwen;
      assign regwen_types[13] = NotRegwen;
      assign regwen_types[14] = NotRegwen;
      assign regwen_types[15] = NotRegwen;
      assign regwen_types[16] = NotRegwen;
      assign regwen_types[17] = NotRegwen;
      assign regwen_types[18] = NotRegwen;
      assign regwen_types[19] = NotRegwen;
      assign regwen_types[20] = NotRegwen;
      assign regwen_types[21] = NotRegwen;
      assign regwen_types[22] = NotRegwen;
      assign regwen_types[23] = NotRegwen;
      assign regwen_types[24] = NotRegwen;
      assign regwen_types[25] = NotRegwen;
      assign regwen_types[26] = NotRegwen;
      assign regwen_types[27] = NotRegwen;
      assign regwen_types[28] = NotRegwen;
      assign regwen_types[29] = NotRegwen;
      assign regwen_types[30] = NotRegwen;
      assign regwen_types[31] = NotRegwen;
      assign regwen_types[32] = NotRegwen;
      assign regwen_types[33] = NotRegwen;
      assign regwen_types[34] = NotRegwen;
      assign regwen_types[35] = NotRegwen;
      assign regwen_types[36] = NotRegwen;
      assign regwen_types[37] = NotRegwen;
      assign regwen_types[38] = NotRegwen;
      assign regwen_types[39] = NotRegwen;
      assign regwen_types[40] = NotRegwen;
      assign regwen_types[41] = NotRegwen;
      assign regwen_types[42] = NotRegwen;
      assign regwen_types[43] = NotRegwen;
      assign regwen_types[44] = NotRegwen;
      assign regwen_types[45] = NotRegwen;
      assign regwen_types[46] = NotRegwen;
      assign regwen_types[47] = NotRegwen;
      assign regwen_types[48] = NotRegwen;
      assign regwen_types[49] = NotRegwen;
      assign regwen_types[50] = NotRegwen;
      assign regwen_types[51] = NotRegwen;
      assign regwen_types[52] = NotRegwen;
      assign regwen_types[53] = NotRegwen;
      assign regwen_types[54] = NotRegwen;
      assign regwen_types[55] = NotRegwen;
      assign regwen_types[56] = NotRegwen;
      assign regwen_types[57] = NotRegwen;
      assign regwen_types[58] = NotRegwen;
      assign regwen_types[59] = NotRegwen;

  typedef enum bit {
    FpvDefault,
    FpvRw0c
  } fpv_reg_access_e;
  fpv_reg_access_e access_policy [61];

  // for write HRO registers, store the write data into exp_vals
  always_ff @(negedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
       oob_addr_err <= 1'b0;
       pend_trans <= '0;
       exp_vals[0] <= 'h0;
       access_policy[0] <= FpvDefault;
       exp_vals[1] <= 'h0;
       access_policy[1] <= FpvDefault;
       exp_vals[2] <= 'h0;
       access_policy[2] <= FpvDefault;
       exp_vals[3] <= 'h0;
       access_policy[3] <= FpvDefault;
       exp_vals[4] <= 'h0;
       access_policy[4] <= FpvDefault;
       exp_vals[5] <= 'h7f;
       access_policy[5] <= FpvDefault;
       exp_vals[6] <= 'h0;
       access_policy[6] <= FpvDefault;
       exp_vals[7] <= 'h0;
       access_policy[7] <= FpvDefault;
       exp_vals[8] <= 'h0;
       access_policy[8] <= FpvDefault;
       exp_vals[9] <= 'h0;
       access_policy[9] <= FpvDefault;
       exp_vals[10] <= 'h0;
       access_policy[10] <= FpvDefault;
       exp_vals[11] <= 'h0;
       access_policy[11] <= FpvDefault;
       exp_vals[12] <= 'h0;
       access_policy[12] <= FpvDefault;
       exp_vals[13] <= 'h0;
       access_policy[13] <= FpvDefault;
       exp_vals[14] <= 'h0;
       access_policy[14] <= FpvDefault;
       exp_vals[15] <= 'h0;
       access_policy[15] <= FpvDefault;
       exp_vals[16] <= 'h0;
       access_policy[16] <= FpvDefault;
       exp_vals[17] <= 'h0;
       access_policy[17] <= FpvDefault;
       exp_vals[18] <= 'h0;
       access_policy[18] <= FpvDefault;
       exp_vals[19] <= 'h0;
       access_policy[19] <= FpvDefault;
       exp_vals[20] <= 'h0;
       access_policy[20] <= FpvDefault;
       exp_vals[21] <= 'h7000;
       access_policy[21] <= FpvDefault;
       exp_vals[22] <= 'h7000;
       access_policy[22] <= FpvDefault;
       exp_vals[23] <= 'h7000;
       access_policy[23] <= FpvDefault;
       exp_vals[24] <= 'h7000;
       access_policy[24] <= FpvDefault;
       exp_vals[25] <= 'h7000;
       access_policy[25] <= FpvDefault;
       exp_vals[26] <= 'h7000;
       access_policy[26] <= FpvDefault;
       exp_vals[27] <= 'h7000;
       access_policy[27] <= FpvDefault;
       exp_vals[28] <= 'h7000;
       access_policy[28] <= FpvDefault;
       exp_vals[29] <= 'h7000;
       access_policy[29] <= FpvDefault;
       exp_vals[30] <= 'h7000;
       access_policy[30] <= FpvDefault;
       exp_vals[31] <= 'h7000;
       access_policy[31] <= FpvDefault;
       exp_vals[32] <= 'h7000;
       access_policy[32] <= FpvDefault;
       exp_vals[33] <= 'h7000;
       access_policy[33] <= FpvDefault;
       exp_vals[34] <= 'h7000;
       access_policy[34] <= FpvDefault;
       exp_vals[35] <= 'h7000;
       access_policy[35] <= FpvDefault;
       exp_vals[36] <= 'h7000;
       access_policy[36] <= FpvDefault;
       exp_vals[37] <= 'h7000;
       access_policy[37] <= FpvDefault;
       exp_vals[38] <= 'h7000;
       access_policy[38] <= FpvDefault;
       exp_vals[39] <= 'h7000;
       access_policy[39] <= FpvDefault;
       exp_vals[40] <= 'h7000;
       access_policy[40] <= FpvDefault;
       exp_vals[41] <= 'h7000;
       access_policy[41] <= FpvDefault;
       exp_vals[42] <= 'h7000;
       access_policy[42] <= FpvDefault;
       exp_vals[43] <= 'h7000;
       access_policy[43] <= FpvDefault;
       exp_vals[44] <= 'h7000;
       access_policy[44] <= FpvDefault;
       exp_vals[45] <= 'h0;
       access_policy[45] <= FpvDefault;
       exp_vals[46] <= 'h0;
       access_policy[46] <= FpvDefault;
       exp_vals[47] <= 'h0;
       access_policy[47] <= FpvDefault;
       exp_vals[48] <= 'h0;
       access_policy[48] <= FpvDefault;
       exp_vals[49] <= 'h0;
       access_policy[49] <= FpvDefault;
       exp_vals[50] <= 'h0;
       access_policy[50] <= FpvDefault;
       exp_vals[51] <= 'h0;
       access_policy[51] <= FpvDefault;
       exp_vals[52] <= 'h0;
       access_policy[52] <= FpvDefault;
       exp_vals[53] <= 'h0;
       access_policy[53] <= FpvDefault;
       exp_vals[54] <= 'h0;
       access_policy[54] <= FpvDefault;
       exp_vals[55] <= 'h0;
       access_policy[55] <= FpvDefault;
       exp_vals[56] <= 'h0;
       access_policy[56] <= FpvDefault;
       exp_vals[57] <= 'h0;
       access_policy[57] <= FpvDefault;
       exp_vals[58] <= 'h0;
       access_policy[58] <= FpvDefault;
       exp_vals[59] <= 'h0;
       access_policy[59] <= FpvDefault;
       exp_vals[60] <= 'h0;
       access_policy[60] <= FpvDefault;
    end else begin
      oob_addr_err <= 1'b0;
      if (h2d.a_valid && d2h.a_ready) begin
        if ((normalized_addr inside {[0:2100]})
            || (normalized_addr inside {[4096: (4096+848*8)]})
            || (normalized_addr inside {[7680: (7680+112*8)]})
           ) begin
          pend_trans[a_source_idx].addr <= normalized_addr;
          if (h2d.a_opcode inside {PutFullData, PutPartialData}) begin
            pend_trans[a_source_idx].wr_data <= h2d.a_data & a_mask_bit;
            pend_trans[a_source_idx].wr_pending <= 1'b1;
          end else if (h2d.a_opcode == Get) begin
            pend_trans[a_source_idx].rd_pending <= 1'b1;
          end
        end else begin
          oob_addr_err <= 1'b1;
        end
      end
      if (d2h.d_valid) begin
        if (pend_trans[d_source_idx].wr_pending == 1) begin
          if (!d2h.d_error && regwen[hro_idx]) begin
            if (access_policy[hro_idx] == FpvRw0c) begin
              // Assume FpvWr0c policy only has one field that is wr0c.
              unique case (regwen_types[hro_idx])
                MuBi4Regwen:
                  exp_vals[hro_idx] <=
                    mubi4_and_hi(mubi4_t'(exp_vals[hro_idx][3:0]),
                                 mubi4_t'(pend_trans[d2h.d_source].wr_data[3:0]));
                MuBi8Regwen:
                  exp_vals[hro_idx] <=
                    mubi8_and_hi(mubi8_t'(exp_vals[hro_idx][7:0]),
                                 mubi8_t'(pend_trans[d2h.d_source].wr_data[7:0]));
                MuBi12Regwen:
                  exp_vals[hro_idx] <=
                    mubi12_and_hi(mubi12_t'(exp_vals[hro_idx][11:0]),
                                  mubi12_t'(pend_trans[d2h.d_source].wr_data[11:0]));
                MuBi16Regwen:
                  exp_vals[hro_idx] <=
                    mubi16_and_hi(mubi16_t'(exp_vals[hro_idx][15:0]),
                                  mubi16_t'(pend_trans[d2h.d_source].wr_data[15:0]));
                default:
                  exp_vals[hro_idx] <=
                    exp_vals[hro_idx][0] ? pend_trans[d2h.d_source].wr_data : 0;
              endcase
            end else begin
              exp_vals[hro_idx] <= pend_trans[d_source_idx].wr_data;
            end
          end
          pend_trans[d_source_idx].wr_pending <= 1'b0;
        end
        if (h2d.d_ready && pend_trans[d_source_idx].rd_pending == 1) begin
          pend_trans[d_source_idx].rd_pending <= 1'b0;
        end
      end
    end
  end

  // for read HRO registers, assert read out values by access policy and exp_vals
  `ASSERT(intr_enable_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h4) |->
          (d2h.d_error ||
           (d2h.d_data & 'hff) ==
            (exp_vals[0] & 'hff)))
  `ASSERT(cfg_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h14) |->
          (d2h.d_error ||
           (d2h.d_data & 'h100000c) ==
            (exp_vals[3] & 'h100000c)))
  `ASSERT(intercept_en_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h1c) |->
          (d2h.d_error ||
           (d2h.d_data & 'hf) ==
            (exp_vals[4] & 'hf)))
  `ASSERT(jedec_cc_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h2c) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffff) ==
            (exp_vals[5] & 'hffff)))
  `ASSERT(jedec_id_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h30) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffff) ==
            (exp_vals[6] & 'hffffff)))
  `ASSERT(read_threshold_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h34) |->
          (d2h.d_error ||
           (d2h.d_data & 'h3ff) ==
            (exp_vals[7] & 'h3ff)))
  `ASSERT(mailbox_addr_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h38) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[8] & 'hffffffff)))
  `ASSERT(cmd_filter_0_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h4c) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[9] & 'hffffffff)))
  `ASSERT(cmd_filter_1_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h50) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[10] & 'hffffffff)))
  `ASSERT(cmd_filter_2_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h54) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[11] & 'hffffffff)))
  `ASSERT(cmd_filter_3_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h58) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[12] & 'hffffffff)))
  `ASSERT(cmd_filter_4_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h5c) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[13] & 'hffffffff)))
  `ASSERT(cmd_filter_5_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h60) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[14] & 'hffffffff)))
  `ASSERT(cmd_filter_6_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h64) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[15] & 'hffffffff)))
  `ASSERT(cmd_filter_7_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h68) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[16] & 'hffffffff)))
  `ASSERT(addr_swap_mask_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h6c) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[17] & 'hffffffff)))
  `ASSERT(addr_swap_data_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h70) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[18] & 'hffffffff)))
  `ASSERT(payload_swap_mask_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h74) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[19] & 'hffffffff)))
  `ASSERT(payload_swap_data_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h78) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[20] & 'hffffffff)))
  `ASSERT(cmd_info_0_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h7c) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[21] & 'h83ffffff)))
  `ASSERT(cmd_info_1_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h80) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[22] & 'h83ffffff)))
  `ASSERT(cmd_info_2_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h84) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[23] & 'h83ffffff)))
  `ASSERT(cmd_info_3_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h88) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[24] & 'h83ffffff)))
  `ASSERT(cmd_info_4_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h8c) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[25] & 'h83ffffff)))
  `ASSERT(cmd_info_5_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h90) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[26] & 'h83ffffff)))
  `ASSERT(cmd_info_6_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h94) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[27] & 'h83ffffff)))
  `ASSERT(cmd_info_7_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h98) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[28] & 'h83ffffff)))
  `ASSERT(cmd_info_8_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h9c) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[29] & 'h83ffffff)))
  `ASSERT(cmd_info_9_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'ha0) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[30] & 'h83ffffff)))
  `ASSERT(cmd_info_10_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'ha4) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[31] & 'h83ffffff)))
  `ASSERT(cmd_info_11_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'ha8) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[32] & 'h83ffffff)))
  `ASSERT(cmd_info_12_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'hac) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[33] & 'h83ffffff)))
  `ASSERT(cmd_info_13_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'hb0) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[34] & 'h83ffffff)))
  `ASSERT(cmd_info_14_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'hb4) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[35] & 'h83ffffff)))
  `ASSERT(cmd_info_15_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'hb8) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[36] & 'h83ffffff)))
  `ASSERT(cmd_info_16_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'hbc) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[37] & 'h83ffffff)))
  `ASSERT(cmd_info_17_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'hc0) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[38] & 'h83ffffff)))
  `ASSERT(cmd_info_18_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'hc4) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[39] & 'h83ffffff)))
  `ASSERT(cmd_info_19_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'hc8) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[40] & 'h83ffffff)))
  `ASSERT(cmd_info_20_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'hcc) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[41] & 'h83ffffff)))
  `ASSERT(cmd_info_21_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'hd0) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[42] & 'h83ffffff)))
  `ASSERT(cmd_info_22_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'hd4) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[43] & 'h83ffffff)))
  `ASSERT(cmd_info_23_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'hd8) |->
          (d2h.d_error ||
           (d2h.d_data & 'h83ffffff) ==
            (exp_vals[44] & 'h83ffffff)))
  `ASSERT(cmd_info_en4b_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'hdc) |->
          (d2h.d_error ||
           (d2h.d_data & 'h800000ff) ==
            (exp_vals[45] & 'h800000ff)))
  `ASSERT(cmd_info_ex4b_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'he0) |->
          (d2h.d_error ||
           (d2h.d_data & 'h800000ff) ==
            (exp_vals[46] & 'h800000ff)))
  `ASSERT(cmd_info_wren_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'he4) |->
          (d2h.d_error ||
           (d2h.d_data & 'h800000ff) ==
            (exp_vals[47] & 'h800000ff)))
  `ASSERT(cmd_info_wrdi_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'he8) |->
          (d2h.d_error ||
           (d2h.d_data & 'h800000ff) ==
            (exp_vals[48] & 'h800000ff)))
  `ASSERT(tpm_cfg_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h804) |->
          (d2h.d_error ||
           (d2h.d_data & 'h1f) ==
            (exp_vals[49] & 'h1f)))
  `ASSERT(tpm_access_0_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h80c) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[50] & 'hffffffff)))
  `ASSERT(tpm_access_1_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h810) |->
          (d2h.d_error ||
           (d2h.d_data & 'hff) ==
            (exp_vals[51] & 'hff)))
  `ASSERT(tpm_sts_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h814) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[52] & 'hffffffff)))
  `ASSERT(tpm_intf_capability_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h818) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[53] & 'hffffffff)))
  `ASSERT(tpm_int_enable_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h81c) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[54] & 'hffffffff)))
  `ASSERT(tpm_int_vector_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h820) |->
          (d2h.d_error ||
           (d2h.d_data & 'hff) ==
            (exp_vals[55] & 'hff)))
  `ASSERT(tpm_int_status_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h824) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[56] & 'hffffffff)))
  `ASSERT(tpm_did_vid_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h828) |->
          (d2h.d_error ||
           (d2h.d_data & 'hffffffff) ==
            (exp_vals[57] & 'hffffffff)))
  `ASSERT(tpm_rid_rd_A,
          (d2h.d_valid && pend_trans[d_source_idx].rd_pending &&
           pend_trans[d_source_idx].addr == 13'h82c) |->
          (d2h.d_error ||
           (d2h.d_data & 'hff) ==
            (exp_vals[58] & 'hff)))

  `ASSERT(TlulOOBAddrErr_A, oob_addr_err |-> s_eventually(d2h.d_valid && d2h.d_error))

  `ifdef UVM
    initial forever begin
      bit csr_assert_en;
      uvm_config_db#(bit)::wait_modified(null, "%m", "csr_assert_en");
      if (!uvm_config_db#(bit)::get(null, "%m", "csr_assert_en", csr_assert_en)) begin
        `uvm_fatal("csr_assert", "Can't find csr_assert_en")
      end
      disable_sva = !csr_assert_en;
    end
  `endif

`endif
`endif
endmodule

`undef REGWEN_PATH

